### ISSUE TITLE
Can the list of repos be optional?

### ISSUE THREAD

**Issue by KyleKing** [dlvhdr/gh-prs#22]
It looks like specifying the repos is required from my local testing. i wanted to match the default Github PRs tab with the below snippet, but no PRs were matched

```yaml
- title: Created
  filters: author:@me
- title: Assigned
  filters: assignee:@me
- title: Mentioned
  filters: mentions:@me
- title: Reviewed Requested
  filters: review-requested:@me
```

I confirmed that specifying one or more repos does work though:

```yaml
- title: Created
  repos:
    - KyleKing/commitizen
    - timothycrosley/pdocs
  filters: author:@me
```

I assume this would require pulling a list of repos if the repos list is empty here: https://github.com/dlvhdr/gh-prs/blob/37e60a8409b2ba5c46d52e9ea00d5a94cbaa2d73/ui/section.go#L43
