### ISSUE TITLE
[bug] bad output when using `is:issue` as a filter

### ISSUE THREAD

**Issue by micalevisk** [dlvhdr/gh-prs#28]
<details>
<summary><code>sections.yml</code></summary>

```yaml
- title: My Pull Requests
  repos:
    - dlvhdr/gh-prs
  filters: is:issue
```

</details>

![image](https://user-images.githubusercontent.com/13461315/145728194-54943bb4-027c-4125-a93d-93c46ecbb394.png)

I think you just need to drop occurrences of `"is:issue"` filter on `filters`

---

I whish I could use this awesome extension with issues as well :/ but yeah, the name implies that's only for PRs, I know.
