### ISSUE TITLE
Leading space on PR's title

### ISSUE THREAD

**Issue by micalevisk** [dlvhdr/gh-prs#29]
<details>
<summary><code>sections.yml</code></summary>

```yaml
- title: NestJS core team's PRs
  filters: -author:app/dependabot -author:app/renovate is:open author:kamilmysliwiec author:jmcdo29 author:BrunnerLivio author:nartc author:johnbiundo author:MarkPieszak author:thomrick author:valorkin
  repos:
    - nestjs/swagger
    - nestjs/awesome-nestjs
    - nestjs/nest-cli
    - nestjs/docs.nestjs.com
    - nestjs/bull
    - nestjs/event-emitter
    - nestjs/serve-static
    - nestjs/axios
    - nestjs/jwt
    - nestjs/terminus
    - nestjs/schematics
    - nestjs/schedule
    - nestjs/graphql
    - nestjs/config
    - nestjs/mapped-types
    - nestjs/typeorm
    - nestjs/throttler
    - nestjs/passport
    - nestjs/nest
```

![image](https://user-images.githubusercontent.com/13461315/145728819-07311395-d17c-4611-be4a-c3b9b477ddc2.png)

Here's the PR:  
`https://github.com/nestjs/nest/pull/1407`

It doesn't have that leading space (or maybe GitHub fixed it in their UI?)

---

- **OS**: Ubuntu 20.04
