### ISSUE TITLE
[feature request] turn the fetch limit configurable

### ISSUE THREAD

**Issue by micalevisk** [dlvhdr/gh-prs#66]
**Is your feature request related to a problem? Please describe.**

As of now, the list of prs have a fixed amount of items, which is 20:

https://github.com/dlvhdr/gh-prs/blob/8f0960b85066ddce51a897d0373da8db2c1f309e/data/api.go#L13

**Describe the solution you'd like**

Make that limit configurable (20 by default) via the config file. Any integer value from 0 to 100 (the limit of GitHub API). You could thrown an error if that value is out of bound or just take the min value from `20` and user's `limit`.

Looks like making it per section would be feasible

https://github.com/dlvhdr/gh-prs/blob/8f0960b85066ddce51a897d0373da8db2c1f309e/ui/section.go#L40

So we can define it like this _(just an ideia)_:

```yaml
prSections:
  - title: My Pull Requests
    filters: is:open author:@me
    limit: 40
  - title: Needs My Review
    filters: is:open review-requested:@me
defaults:
  list:
    limit: 10
  preview:
    open: true
    width: 60
```
