### ISSUE TITLE
Few repository names are blank

### ISSUE THREAD

**Issue by micalevisk** [dlvhdr/gh-prs#72]
For whatever reason, the repo name doesn't appear on few PRs. When I open it with <kbd>o</kbd> it works fine. See:

![image](https://user-images.githubusercontent.com/13461315/149592932-49db6799-1f95-4300-9d84-ea71923d6de3.png)

This happens with various repos. Also, They are public ones. The preview window works fine.

With the following config:

```yaml
defaults:
  prsLimit: 20
  preview:
    open: false
    width: 120

prSections:
  - title: All on @nestjs
    filters: 'is:open -reviewed-by:@me draft:false -author:app/dependabot -author:app/renovate -author:@me org:nestjs'
    limit: 33
```

---

- OS: Ubuntu
- extension version: v2.1.0
